### PR TITLE
Add popover description for User-agent rotation.

### PR DESCRIPTION
**Pull request by arch-btw**
The popover  for user agent rotation was missing.

### CODE REVIEW

**Comment by vladimiry** [comment]
Thanks for the good finding. Originally there was "App restart required for the option to take effect." popup but got accidentally lost some time ago, so I did append the value.

**Comment by vladimiry** [comment]
Btw, the default user agents list got recently updated in 1cf2ab6aab37dbcc837d1d8eeb62a3c4213a537c.

**Comment by vladimiry** [comment]
If you need it, the recent build uploaded [here](https://mega.nz/folder/N45hzQ6C#ciaN_jLuU9Nv5AH6RC9UnA).

**Comment by arch-btw** [comment]
@vladimiry Thank you so much for appending! And thank you for updating the user agent list and the download link!
I really appreciate it!
Keep up the great work!

**Pull request merged**
