### PR TITLE
AUR and snap store links

### PR DESCRIPTION
**Pull request by joshirio**
update links and add missing article

### CODE REVIEW

**Comment by vladimiry** [comment]
Can you add `[skip ci]` to the commit message and set the version in package.json to
 3.0.1 in?

**Comment by joshirio** [comment]
done
is this fine the way it is now?

**Comment by vladimiry** [comment]
>  is this fine the way it is now?

Not really. `[skip ci]` is just not to trigger a new build on CI servers as it's not needed for the case. package.json update is more like for clarity.

Thanks for the update.

**Comment by vladimiry** [comment]
Hi @flexiondotorg. I noticed you are a Protoinmail user and work on the Snapcraft team. So I thought if you tried the ElectronMail app and liked it maybe you could consider featuring the app as an editors pick. This project provides some unique features as for example offline mails access since [v2.0.0](https://github.com/vladimiry/ElectronMail/releases/tag/v2.0.0), [full-text search](https://github.com/vladimiry/ElectronMail/issues/92) and [built-in web client](https://github.com/vladimiry/ElectronMail/issues/79) (see more in readme file). Besides the snap package has got some specific improvements which made it more usable (see: https://github.com/vladimiry/ElectronMail/issues/104, https://github.com/vladimiry/ElectronMail/pull/109, https://github.com/vladimiry/ElectronMail/issues/48#issuecomment-472321885). The snap store link is here https://snapcraft.io/electron-mail.

**Comment by vladimiry** [comment]
@joshirio I tweaked the readme file today, can you update the snap package description (I seem to have no access to editing it)?

**Comment by joshirio** [comment]
@vladimiry I'm sorry, forgot to add you to the collaborators list after the rename. Please feel free to edit, I'll add you.

**Comment by vladimiry** [comment]
Thanks, will try not to break things there :)

**Comment by vladimiry** [comment]
I see that being featured makes a real difference, the installations count grows quite fast.

**Comment by flexiondotorg** [comment]
Yep, we updated the featured apps a couple of days ago. I am using Electron Mail 😀

**Comment by vladimiry** [comment]
@flexiondotorg this is not the best place to share feedback, but just a quick one. I noticed that when I edit the description of the package at the snap store and then click preview the links look fine, but links were not rendered well for the published package. So the preview feature doesn't really reflect the reality and this makes it impossible to copy-paste the markdown content from the readme :)

**Comment by vladimiry** [comment]
@joshirio if you were considering publishing v3.3.0 to repositories I think it's safe to do. There are two reasons I published v3.3.0 as pre-release:
- AppImage and Snap packages are still based on Electron 4. Related issue is [here](https://github.com/vladimiry/ElectronMail/issues/134).
- The auto-update feature got disabled with the release and so users that have installed previous app versions would most likely start getting errors on app start if that would be a stable release as this release doesn't include the files auto-update feature requests during checking new updates availability.

So I'm going to keep publishing new releases as pre-releases for some time and I believe that should not be a reason not to update Snap/Pacman repositories.

**Comment by joshirio** [comment]
Fine, I'll update the packages, thanks for the info.

**Pull request merged**
