### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by macbugs**
Fix for corrupted small icons in Finder view

### CODE REVIEW

**Comment by vladimiry** [comment]
Did you actually test the fix in action?

**Comment by macbugs** [comment]
Yes - when I duplicate the application bundle, the icon is no longer corrupted

**Comment by vladimiry** [comment]
The notification icon is currently dynamic. Meaning it's generated based on the [colors customization](https://github.com/vladimiry/ElectronMail/issues/376#issuecomment-786484142) settings and then set to [Notification.image](https://developer.mozilla.org/en-US/docs/Web/API/Notification/image) as a DataURL. So it doesn't look like this change could actually fix the desktop notification icon. There would be a need to switch to a static image first at least to test the case in action so I tend to think you didn't test the notification icon case.

There is a small chance though that @chromium doesn't respect the specified `Notification.image` value and uses the default bundle image. This would be a @chromium bug.

**Comment by vladimiry** [comment]
> I will submit a separate patch for that

Can we discuss first what the patch is going to be? So we reduce the chance to waste the time.

Are you going to point `Notification.image` to a static `src/assets/dist/icons/mac/icon.icns` file in order to test the case in action? If you do this test I think it would be ok to sacrifice/drop the "dynamic notification icon" feature in order to close #185.

**Comment by vladimiry** [comment]
I mean it's not required you make the `Notification.image uses src/assets/dist/icons/mac/icon.icns file` patch but test this case in action. If it works I could handle the code change. If it's complicated for you to test this case in action (building stuff from sources), I could prepare a test build.

**Comment by macbugs** [comment]
No, I believe the image file contains some extra bytes (invalid data.)  What graphics program was used to create/save this PNG ?

**Comment by vladimiry** [comment]
> What graphics program was used to create/save this PNG ?

Don't remember exactly but I think I made a screenshot first from OpenOffice editor to get https://github.com/vladimiry/ElectronMail/blob/master/src/assets/icon/icon.png from (.odt source file located in the same folder). And then I used some CLI tool to generate the PNGs of different sizes (it likely was some CLI package from https://www.npmjs.com but I don't remember exactly).

Is the https://github.com/vladimiry/ElectronMail/blob/master/src/assets/icon/icon.png also broken by those extra/invalid bytes (source file)?

**Comment by macbugs** [comment]
both of these files appear to be valid
```
https://github.com/vladimiry/ElectronMail/blob/master/src/assets/icon/icon.png
https://github.com/vladimiry/ElectronMail/blob/master/src/assets/dist/icons/icon.png
```
strangely the notification icon glitch looks identical to the app icon glitch, so I thought it was the same bug...



...but I cannot reproduce the notification bug, so I guess that is already fixed
Screen Shot 2022-04-13 at 06 19 20
So you are correct - this pull request only fixes the app icon glitch

**Comment by vladimiry** [comment]
>  ...but I cannot reproduce the notification bug, so I guess that is already fixed

Can you change the icon color using https://github.com/vladimiry/ElectronMail/issues/376#issuecomment-786484142 setting using https://github.com/vladimiry/ElectronMail/releases/tag/v4.13.6? So the color is not default and we know for sure that the customized dynamic icon is actually use for notifications. Asking since it might potentially be that on macOS a custom `Notification.image` image gets ignored.

After this test if the issue is still there (it's supposed to be there based on the https://github.com/vladimiry/ElectronMail/issues/199#issuecomment-1094122638 if this test was valid) I can switch the `Notification.image` to a static `src/assets/dist/icons/mac/icon.icns` and we see if it makes an effect.

**Comment by vladimiry** [comment]
Thanks. So macOS displays 2 icons in the notification. One is static and second is specified as [Notification.image](https://developer.mozilla.org/en-US/docs/Web/API/Notification/image). This is a weird behavior in my opinion. Anyway, I'm going to make the icon static and close both #185 and #199.

**Comment by vladimiry** [comment]
The change has been pushed to the `wip` branch (see b822508eb853ab5e4e6be96a1833a8a629fa3850). Thanks for contribution.

**Comment by macbugs** [comment]
> **This is a weird behavior in my opinion.**

Yes, all of the other notifications look similar to this example...
image

...but here the extra icon seems to be some kind of anchor or "place holder" for additional information which could fit in the window...

https://user-images.githubusercontent.com/101867641/163191581-3496b105-52c3-4e05-a8a2-9b2fd28a5f3e.mov
https://user-images.githubusercontent.com/101867641/163191615-f53294d2-dc6b-499f-8ebf-3ff0a3bf6300.mov

**Comment by vladimiry** [comment]
> but here the extra icon

I just dropped it. Lets see what happens.

**Comment by vladimiry** [comment]
@macbugs can you test [this]() build?

Changes:
- Include the ".icns" image fix.
- The `Notification.image/icon` not being set on macOS system. I assume that on macOS the ".icns" image is used a default notification icon. The `Notification.icon` is still set on Linux/Win systems and now it's a static image. At least on Linux if the `Notification.icon` value not set then the default @electron icon gets displayed (also tested the `Notification.image` on Linux and got no effect, it still ends up with a default @electron icon).

**Comment by macbugs** [comment]
Screen Shot 2022-04-13 at 17 51 15
[a notification sound is played, but the message does not appear on screen - it is only visible when I open the notification history]
Screen Shot 2022-04-13 at 18 05 25
electron-mail-2022-04-13-v4.14.0-wip
___________
Screen Shot 2022-04-13 at 17 55 37
[a sound is played and the notification appears on screen for 1 second]
Screen Shot 2022-04-13 at 18 17 12
electron-mail-2022-04-13-v4.14.0-wip-2
_____
The app icon is normal on both of these builds
Screen Shot 2022-04-13 at 17 52 50

**Comment by vladimiry** [comment]
Thanks.

>  [a notification sound is played, but the message does not appear on screen - it is only visible when I open the notification history]

Interesting. So macOS acts differently if the notification icon is not specified.

What is the expected/regular notification behavior on macOS (` electron-mail-2022-04-13-v4.14.0-wip` vs ` electron-mail-2022-04-13-v4.14.0-wip-2`)?

**Comment by macbugs** [comment]
> **_What is the expected/regular notification behavior?_**

wip-2 is more common... however, if an app supports notifications, the user can customize the behavior, like [this](https://support.apple.com/en-ca/HT204079).  The defaults for ElectronMail look like this:[
](https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/notifications/)

Screen Shot 2022-04-14 at 00 36 56
The developer can also customize notifications to some extent, for example, a notification can include [activity buttons](https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/notifications/).
image
I have never previously witnessed the behavior depicted [here](https://github.com/vladimiry/ElectronMail/pull/503#issuecomment-1098060094) in this movie before, it was a complete surprise.  I am intrigued by this undocumented feature since alerts usually look like this:

**Comment by vladimiry** [comment]
> wip-2 is more common

Thanks. So lets stick to this option. This also means no platform-specific code logic (preferred option), ie notifications on all platforms get the icon `Notification.icon` specified.

**Pull request closed without merging**
